language: python
python:
- '2.7'
install: pip install -r requirements.txt --use-mirrors
before_script:
- psql -c 'create database civic_json_worker_test;' -U postgres
script: python run_update_test.py
notifications:
  webhooks: http://project-monitor.codeforamerica.org/projects/72d031cc-8f21-4968-8db6-ff7370f5e98b/status